import { VTNode } from "../../vtsParser.js";
import { NodeInfo } from "../vtsGenerator.js";

type IRArg = { type: "node"; value: IREvent } | { type: "value"; value: any } | { type: "array"; value: IRArg[] };

interface IREvent {
	method: string;
	args: IRArg[];
	ids: number[];
}

interface IREventList {
	events: IREvent[];
	startCondition?: IRConditional;
}

interface IRSequence {
	name: string;
	id: number;
	events: IREventList[];
}

interface IRConditional {
	method: string;
	args: any[];
	multiMethod: { method: string; args: any[] }[];
}

interface IRConditionalAction {
	id: number;
	name: string;

	if: IRConditional;
	then: IREvent[];
	elseIfs: { conditional: IRConditional; then: IREvent[] }[];
	else: IREvent[];
}

interface IRGV {
	id: number;
	defaultValue: number;
	name: string;
}

interface IR {
	sequences: IRSequence[];
	conditionalActions: IRConditionalAction[];
	gvs: IRGV[];
}

class IRGenerator {
	private nodeInfosMap: Record<number, NodeInfo> = {};
	constructor(private vts: VTNode, private nodeInfos: NodeInfo[]) {
		nodeInfos.forEach(nodeInfo => {
			if (nodeInfo.result) this.nodeInfosMap[nodeInfo.result.id] = nodeInfo;
		});
	}

	private parseArg(arg: any): IRArg {
		// const argAsNodeInfo = this.nodeInfos.find(n => n.result == arg);
		const argAsNodeInfo = this.nodeInfosMap[arg?.id];
		if (argAsNodeInfo) {
			const args = argAsNodeInfo.arguments.map(a => this.parseArg(a));
			return { type: "node", value: { method: argAsNodeInfo.methodName, args: args, ids: argAsNodeInfo.ids } };
		}

		if (Array.isArray(arg)) {
			return { type: "array", value: arg.map(a => this.parseArg(a)) };
		}

		return { type: "value", value: arg };
	}

	private parseEventsList(events: VTNode[]): IREventList[] {
		return events.map(eventParent => {
			const eventsNodes = eventParent.getAllChildrenWithName("EventTarget");
			const events = this.parseEvents(eventsNodes);

			let startCondition: IRConditional | undefined = undefined;
			if (eventParent.getValue("conditional")) {
				const conditionalParent = this.vts.getNode("Conditionals");
				const conditionals = conditionalParent.getAllChildrenWithName("CONDITIONAL");
				const conditional = conditionals.find(c => c.getValue("id") == eventParent.getValue("conditional"));

				startCondition = this.parseConditional(conditional);
			}

			return { events, startCondition };
		});
	}

	private parseEvents(events: VTNode[]): IREvent[] {
		return events.map(event => {
			// const nodeInfo = this.nodeInfos.find(n => n.result == event);
			const nodeInfo = this.nodeInfosMap[event.id];
			if (!nodeInfo) {
				return { method: "ERR_UNKNOWN", args: [], ids: [] };
			} else {
				const args = nodeInfo.arguments.map(a => this.parseArg(a));
				return { method: nodeInfo.methodName, args: args, ids: nodeInfo.ids };
			}
		});
	}

	private parseSequence(sequence: VTNode): IRSequence {
		const events = sequence.getAllChildrenWithName("EVENT");
		// Check if this sequence was generated by the compiler or already existed
		// const sequenceInfo = this.nodeInfos.find(n => n.result == sequence);
		const sequenceInfo = this.nodeInfosMap[sequence.id];
		if (!sequenceInfo) return null;

		return {
			name: sequence.getValue("sequenceName"),
			id: sequence.getValue("id"),
			events: this.parseEventsList(events)
		};
	}

	private parseConditional(conditional: VTNode): IRConditional {
		// const conditionalNodeInfo = this.nodeInfos.find(n => n.result == conditional);
		const conditionalNodeInfo = this.nodeInfosMap[conditional.id];
		// const compInfos = conditional.getChildrenWithName("COMP").map(n => this.nodeInfos.find(ni => ni.result == n));
		const compInfos = conditional.getAllChildrenWithName("COMP").map(n => this.nodeInfosMap[n.id]);
		// let result = "";

		if (conditionalNodeInfo) {
			const args = conditionalNodeInfo.arguments.map(a => this.parseArg(a));
			return { method: conditionalNodeInfo.methodName, args: args, multiMethod: [] };
		} else {
			const methods = compInfos.map(info => {
				if (!info) {
					return { method: "ERR_UNKNOWN", args: [] };
				}
				const compArgs = info.arguments.map(a => this.parseArg(a));

				return { method: info.methodName, args: compArgs };
			});

			return { method: null, args: [], multiMethod: methods };
		}
	}

	private parseConditionalAction(action: VTNode) {
		// Check if this action was generated by the compiler or already existed
		// const actionNodeInfo = this.nodeInfos.find(n => n.result == action);
		const actionNodeInfo = this.nodeInfosMap[action.id];
		if (!actionNodeInfo) return null;

		const bb = action.getNode("BASE_BLOCK");
		const name = bb.getValue("{blockName}");
		const conditional = bb.getNode("CONDITIONAL");

		// let condActText = `${name} (${action.getValue("id")})\n\tIF` + this.describeConditional(conditional) + "\n";
		const then = bb.getNode("ACTIONS");
		const thenEvents = this.parseEvents(then.getAllChildrenWithName("EventTarget"));
		const condAct: IRConditionalAction = {
			id: action.getValue("id"),
			name: name as string,
			if: this.parseConditional(conditional),
			then: thenEvents,
			elseIfs: [],
			else: []
		};

		const elseIfBlocks = bb.getAllChildrenWithName("ELSE_IF");
		elseIfBlocks.forEach(elseIf => {
			const elseIfConditional = elseIf.getNode("CONDITIONAL");
			// condActText += `\tELSE_IF ` + this.describeConditional(elseIfConditional) + "\n";

			const elseIfEvents = this.parseEvents(elseIf.getNode("ACTIONS").getAllChildrenWithName("EventTarget"));

			condAct.elseIfs.push({
				conditional: this.parseConditional(elseIfConditional),
				then: elseIfEvents
			});
		});

		const elseEvents = bb.getNode("ELSE_ACTIONS");
		if (elseEvents) {
			const elseEventsDec = this.parseEvents(elseEvents.getAllChildrenWithName("EventTarget"));
			condAct.else = elseEventsDec;
		}

		return condAct;
	}

	private parseGv(gv: VTNode): IRGV {
		const [id, name, _, defaultValue] = gv.getValue("data") as [number, string, string, number];
		return { id, name, defaultValue };
	}

	public generateIR() {
		const sequences = this.vts.getAllChildrenWithName("SEQUENCE");
		const condActions = this.vts.getAllChildrenWithName("ConditionalAction");
		const gvs = this.vts.getAllChildrenWithName("gv");

		const ir: IR = {
			sequences: sequences.map(s => this.parseSequence(s)).filter(s => s != null),
			conditionalActions: condActions.map(ca => this.parseConditionalAction(ca)).filter(ca => ca != null),
			gvs: gvs.map(gv => this.parseGv(gv)).filter(gv => gv != null)
		};

		return ir;
	}

	private static stringifyArg(arg: IRArg, ir: IR) {
		switch (arg.type) {
			case "value": {
				if (typeof arg.value == "number" && arg.value >= 10000) {
					const seqRef = ir.sequences.find(s => s.id == arg.value);
					if (seqRef) {
						return `seq_${seqRef.name}_${seqRef.id}`;
					}
					const cActRef = ir.conditionalActions.find(ca => ca.id == arg.value);
					if (cActRef) {
						return `cact_${cActRef.name}_${cActRef.id}`;
					}
					const gvRef = ir.gvs.find(gv => gv.id == arg.value);
					if (gvRef) {
						return gvRef.name;
					}
				}
				return JSON.stringify(arg.value);
			}
			case "node": {
				return this.stringifyEvent(arg.value, ir);
			}
			case "array": {
				return `[${arg.value.map(a => this.stringifyArg(a, ir)).join(", ")}]`;
			}
			default:
				throw new Error(`Invalid IRArg type: ${arg}`);
		}
	}

	private static stringifyEvent(event: IREvent, ir: IR) {
		const args = event.args.map(a => this.stringifyArg(a, ir));
		return `${event.method}(${args.join(", ")})`;
	}

	private static stringifyConditional(cond: IRConditional, ir: IR) {
		if (cond.method) {
			const args = cond.args.map(a => this.stringifyArg(a, ir));
			return `${cond.method}(${args.join(", ")})`;
		} else {
			const multiMethods = cond.multiMethod.map(m => {
				const args = m.args.map(a => this.stringifyArg(a, ir));
				return `${m.method}(${args.join(", ")})`;
			});

			return multiMethods.join(" + ");
		}
	}

	private static stringifyConditionalAction(ca: IRConditionalAction, ir: IR) {
		let result = "";
		result += `[CACT] ${ca.name} (${ca.id})\n`;
		result += `\tIF ${this.stringifyConditional(ca.if, ir)}\n`;
		ca.then.forEach(e => {
			result += `\t\t${this.stringifyEvent(e, ir)}\n`;
		});

		ca.elseIfs.forEach(elseIf => {
			result += `\tELSE_IF ${this.stringifyConditional(elseIf.conditional, ir)}\n`;
			elseIf.then.forEach(e => {
				result += `\t\t${this.stringifyEvent(e, ir)}\n`;
			});
		});

		if (ca.else.length > 0) {
			result += `\tELSE\n`;
			ca.else.forEach(e => {
				result += `\t\t${this.stringifyEvent(e, ir)}\n`;
			});
		}
		result += "\n";

		return result;
	}

	public static debug(ir: IR) {
		let result = ``;
		ir.sequences.forEach(s => {
			result += `[SEQ] ${s.name} (${s.id})\n`;
			s.events.forEach(eventList => {
				if (eventList.startCondition) {
					result += `\tWAIT_UNTIL ${this.stringifyConditional(eventList.startCondition, ir)}\n`;
				}
				eventList.events.forEach(e => {
					result += `\t${this.stringifyEvent(e, ir)}\n`;
				});
			});
			result += "\n";
		});

		// Conditional Actions (with push/pop at the end)
		ir.conditionalActions.forEach(ca => {
			if (ca.name == "push" || ca.name == "pop") return;
			result += this.stringifyConditionalAction(ca, ir);
		});
		ir.conditionalActions.forEach(ca => {
			if (ca.name != "push" && ca.name != "pop") return;
			result += this.stringifyConditionalAction(ca, ir);
		});

		ir.gvs.forEach(gv => {
			result += `[GV] ${gv.name} (${gv.id}) = ${gv.defaultValue}\n`;
		});

		return result;
	}
}

export { IRGenerator, IR, IREvent, IRSequence, IRConditional, IRConditionalAction, IRArg, IRGV, IREventList };
